# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'Sonarqube'
    scannerMode: 'MSBuild'
    projectKey: 'App-NetCore_App-NetCore'
    projectName: 'App-Net'

- task: SonarQubeAnalyze@5

- task: SonarQubePublish@5
  inputs:
   pollingTimeoutSec: '300'
   