trigger: none

pool:
  vmImage: macOS-latest

variables:
  - group: secret
  - name: buildConfiguration
    value: 'release'
  - name: versionName
    value: '1.0'
  - name: versionCodeOffset
    value: '0'

stages:
  - stage: Build_Android
    jobs:
      - job:
        displayName: 'Build Android'
        workspace:
          clean: all
        steps:
          - task: Gradle@2
            inputs:
              workingDirectory: '$(Build.SourcesDirectory)'
              gradleWrapperFile: 'gradlew'
              gradleOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.8'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: false
              testResultsFiles: '**/TEST-*.xml'
              tasks: 'assemble$(buildConfiguration)'
          

          - task: AndroidSigning@3
            inputs:
              apkFiles: '**/*.apk' 
              apksign: true
              apksignerKeystoreFile: '$(keystore)'
              apksignerKeystorePassword: '$(keystore.password)'
              apksignerKeystoreAlias: '$(keystore.alias)'
              apksignerKeyPassword: '$(keystore.aliasPassword)'
              apksignerArguments: --out $(Build.SourcesDirectory)/app.release.apk
              zipalign: true

          - task: CopyFiles@2
            inputs:
              SourceFolder: $(Build.SourcesDirectory)
              contents: 'app.release.apk' 
              targetFolder: 'drop/$(buildConfiguration)_android'
              overWrite: true

          - task: PublishBuildArtifacts@1
            inputs:
              pathtoPublish: 'drop/$(buildConfiguration)_android'
              artifactName: '$(buildConfiguration)_android'
              publishLocation: 'container'